config/routes.rb
Rails.application.routes.draw do
  root to: 'budgets#index'
  get "budgets/:id/assign", to: "budgets#assign"
  get "budgets/:id/spend", to: "budgets#spend"
  resources :accounts
  resources :budgets
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :budget

  enum :transaction_type, { expense: 0, allocation: 1, income: 2, transfer: 3 }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy]
  def create
    account = Account.create(account_params)
    redirect_to account_path(account)
  end

  def update
    @account.update(account_params)

    redirect_to account_path(@account)
  end

  def destroy
    @account.destroy
    redirect_to accounts_path
  end

  def show
  end

  def index
    @accounts = Account.all
  end

  def new
    @account = Account.new
  end

  def edit
  end

  private

  def account_params
    params.require(:account).permit(:name, :balance)
  end

  def set_account
    @account = Account.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: %i[show update destroy edit assign spend]

  def create
    budget = Budget.create(budget_params)

    redirect_to budget_path(budget)
  end

  def update
    sum = budget_params[:sum].to_i

    if params[:commit] == 'assign'
      @budget.update(allocated_sum: @budget.allocated_sum + sum)
      transaction = Transaction.new(
        budget: @budget,
        transaction_date: Date.today,
        transaction_type: :allocation,
        amount: sum,
        account_id: 3,
      )
      transaction.save
    elsif params[:commit] == 'spend'
      account = Account.find_by(id: budget_params[:account_id])
      transaction = Transaction.new(
        account: account,
        budget: @budget,
        transaction_date: Date.today,
        amount: sum
      )
      account.update(balance: account.balance - sum)
      @budget.update(allocated_sum: @budget.allocated_sum - sum)
      transaction.save
    else
      @budget.update(budget_params)
    end

    redirect_to budgets_path
  end

  def destroy
    @budget.destroy
    redirect_to budgets_path
  end

  def show
  end

  def index
    @budgets = Budget.all
    @account_options = Account.all.map { |account| [account.name, account.id]}
    @default_account_id = Account.find_by(name: :tnkf).id

    accounts_sum = Account.all.map(&:balance).sum.to_f
    budgets_allocated_sum = Budget.all.map(&:allocated_sum).sum.to_f
    @available_amount = accounts_sum - budgets_allocated_sum
  end

  def new
    @budget = Budget.new
  end

  def edit
  end

  def spend
    @account_options = Account.all.map { |account| [account.name, account.id]}
    @default_account_id = Account.find_by(name: :tnkf).id
    @expenses = Transaction.where(transaction_type: :expense)
  end

  def assign
    @allocations = Transaction.where(transaction_type: :allocation)
  end

  private

  def budget_params
    params.require(:budget).permit(
      :name,
      :account_id,
      :sum
    )
  end

  def set_budget
    @budget = Budget.find(params[:id])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/accounts/_accounts.html.erb
<div class="accounts">
  <% accounts.each do |account| %>
    <div class="accounts_item">
      <p><%= link_to account.name, account_path(account) %></p>
      <p><%= account.balance %></p>
    </div>
    <% end %>
</div>

app/views/accounts/edit.html.erb
<h2>Edit account</h2>

<%= form_with model: @account do |form| %>
  <p>
  <%= form.label :name, 'Name' %>
  </p>
  <p>
  <%= form.text_field :name %>
  </p>
  <p>
  <%= form.label :balance, 'Balance' %>
  </p>
  <p>
  <%= form.text_field :balance %>
  </p>
  <p>
  <%= form.submit 'Save' %>
  </p>
<% end %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<%= link_to 'Create account', new_account_path %>
<%= render 'accounts', accounts: @accounts %>
<%= link_to 'go to budgets', budgets_path %>

app/views/accounts/new.html.erb
<h2>New Account</h2>

<%= form_with model: @account do |form| %>
  <p>
  <%= form.label :name, 'Name' %>
  </p>
  <p>
  <%= form.text_field :name %>
  </p>
  <p>
  <%= form.label :balance, 'Balance' %>
  </p>
  <p>
  <%= form.text_field :balance %>
  </p>
  <p>
  <%= form.submit 'Create' %>
  </p>
<% end %>

app/views/accounts/show.html.erb
<h1>Account</h1>

<p>name: <%= @account.name %></p>
<p>balance: <%= @account.balance %></p>
<div>
<%= link_to 'edit account', edit_account_path(@account) %>
</div>
<br/>
<div>
  <%= button_to 'delete account', account_path(@account), method: :delete %>
</div>
<hr/>
<p><%= link_to 'accounts', accounts_path %></p>

app/views/budgets/_accounts.html.erb
<div class="accounts">
  <% accounts.each do |account| %>
    <div class="accounts_item">
      
      <p><%= link_to account.name, account_path(account) %></p>
      <p><%= account.balance %></p>
    </div>
    <% end %>
</div>

app/views/budgets/_form.html.erb
<%= form_with model: @budget do |form| %>
  <p>
  <%= form.label :name, 'Name' %>
  </p>
  <p>
  <%= form.text_field :name, required: true %>
  </p>
  <p>
  <%= form.submit 'Save' %>
  </p>
<% end %>

app/views/budgets/assign.html.erb
<div class="form_container">
  <div class="operation_form">
    <h3 class="operation_form-title">
      Assign to 
      <b class="operation_form-budget_name">
        <%= @budget.name %>
      </b>
    </h3>
    <%= form_with model: @budget do |form|%>
      <%=  form.number_field :sum, class: "operation_form-field" %>
      <p>(available to spend:<%= @budget.allocated_sum %>)</p>
      <div class="operation_form-actions">
        <%= link_to 'cancel', budgets_path, class: 'operation_form-button' %>
        <%= form.submit 'assign', class: 'operation_form-button' %>
      </div>
    <% end %>
  </div>

  <ul class="allocations">
    <% @allocations.each do |alloc| %>
      <li class="allocations_item">
        <div class="allocations_item-date"><%= alloc.transaction_date %></div>
        <div class="allocations_item-body">
          <span class="allocations_item-account"><%= alloc.account.name %></span>
          <span class="allocations_item-sum"><%= alloc.amount %></span>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/budgets/edit.html.erb
<h2>Edit Budget</h2>

<%= render 'form' %>

app/views/budgets/index.html.erb
<div class="assigning-info">
  <b>
    <%= link_to 'Ready to assign', accounts_path %> 
  </b><%= @available_amount %>
</div>

<div class="budgets_list">
  <% @budgets.each do |budget| %>
    <div class="budgets_item">
        <%= link_to budget.name, budget_path(budget), class: "budgets_item-title" %>
      <div class="budgets_item-body">
        <a href="<%= budget_path(budget)%>/assign" class="budgets_item-button">
          assign
        </a>
        <a href="<%= budget_path(budget)%>/spend" class="budgets_item-button">
          spend
        </a>
      </div>
      <div class="budgets_item-sum">
        <%= budget.allocated_sum || 0 %>
      </div>
      <div class="budgets_item-needed_sum">
        <%= budget.allocated_sum || 0 %>
      </div>
    </div>
  <% end %>
  <div class="budgets_item">
    <%= link_to 'Create budget', new_budget_path, class: 'budgets_item-body' %>
  </div>
</div>

app/views/budgets/new.html.erb
<h2>New Budget</h2>

<%= render 'form' %>

app/views/budgets/show.html.erb
<h1>Budget</h1>

<p>name: <%= @budget.name %></p>
<p>allocated_sum: <%= @budget.allocated_sum %></p>

<div>
<%= link_to 'Edit budget', edit_budget_path(@budget) %>
  
</div>
<br/>
<div>
  <%= button_to 'delete budget', budget_path(@budget), method: :delete %>
</div>
<hr/>

<p><%= link_to 'go to budgets', budgets_path %></p>

app/views/budgets/spend.html.erb
<div class="form_container">
  
  <div class="operation_form">
    <%= form_with model: @budget, class: "operation_form-body" do |form|%>
      <h3 class="operation_form-title">
        Spend to 
        <b class="operation_form-budget_name">
          <%= @budget.name %>
        </b>
        from
        <%= form.select(:account_id, options_for_select(@account_options, selected: @default_account_id), {}, class: "form-field") %>
      </h3>
      <%= form.number_field :sum, class: "operation_form-field" %>
      <div class="operation_form-actions">
        <%= link_to 'cancel', budgets_path, class: "operation_form-button" %>
        <%= form.submit 'spend', class: "operation_form-button" %>
      </div>
    <% end %>
    <p>(available to spend:<%= @budget.allocated_sum %>)</p>
  </div>

  <ul class="expenses">
    <% @expenses.each do |exp| %>
      <li class="expenses_item">
        <div class="expenses_item-date"><%= exp.transaction_date %></div>
        <div class="expenses_item-body">
          <span class="expenses_item-account"><%= exp.account.name %></span>
          <span class="expenses_item-sum"><%= exp.amount %></span>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accounter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>